[package]
name = "algosul-core"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true

[features]
i18n = ["serde", "toml", "strfmt", "sys-locale"]

[dependencies]
serde = { version = "1.*", features = ["derive"], optional = true }
toml = { version = "0.8.23", features = ["parse", "display"], optional = true }
strfmt = { version = "*", optional = true }
sys-locale = { version = "0.3.2", optional = true }
