[toolchain]
channel = "nightly"
components = ["rust-src"]
profile = "default"
targets = [
    # linux
    "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu",
    # windows
    "x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc",
    # apple-darwin
    "x86_64-apple-darwin", "aarch64-apple-darwin",
    # apple-ios
    "x86_64-apple-ios", "aarch64-apple-ios",
    # android
    "x86_64-linux-android", "aarch64-linux-android",
]