name: Multi-Platform Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        arch: [ x86_64, aarch64 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}-unknown-linux-gnu

      - name: Install target (Linux)
        if: matrix.os == 'ubuntu-latest' && matrix.arch != 'x86_64'
        run: rustup target add ${{ matrix.arch }}-unknown-linux-gnu

      - name: Build
        run: |
          cargo build --verbose --target ${{ matrix.arch }}-unknown-linux-gnu

      - name: Run tests
        run: |
          cargo test --verbose --target ${{ matrix.arch }}-unknown-linux-gnu

