name: Deploy Homepage
on:
  push:
    branches: [ release ]
    paths:
      - 'docs/**'
permissions:
  contents: write
  pages: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd docs
          npm install

      - name: Build project
        run: |
          cd docs
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1