name: Update README cards

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - theme: default
            target_theme: light
            locale: en
            target_locale: en
          - theme: dark
            target_theme: dark
            locale: en
            target_locale: en
          - theme: default
            target_theme: light
            locale: cn
            target_locale: zh
          - theme: dark
            target_theme: dark
            locale: cn
            target_locale: zh
    steps:
      - uses: actions/checkout@v4

      - name: Create cards directory
        run: |
          mkdir -p cards

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&locale=${{ matrix.locale }}&theme=${{ matrix.theme }}&hide_border=true&show=prs_merged_percentage&include_all_commits=true&count_private=true&show_icons=true
          path: cards/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate top-langs card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&locale=${{ matrix.locale }}&theme=${{ matrix.theme }}&show_icons=true&hide_border=true&layout=compact
          path: cards/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cards-${{ matrix.target_locale }}-${{ matrix.target_theme }}
          path: cards/*.svg
          
  commit-and-push:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: cards

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add cards/**/*.svg
          git commit -m "[GITHUB ACTIONS] Update README cards" || exit 0
          git push