name: Rust Format Check

on:
  pull_request:
    branches: [ release ]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt

      - name: Run cargo fmt
        run: |
          # First check if formatting is needed
          cargo fmt --all -- --check --config-path code-standards/rustfmt.toml
